# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 23:14


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_wagtailcompanypage_sites_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitformfield',
            name='field_type',
            field=models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time')], max_length=16, verbose_name='field type'),
        ),
    ]
