# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 23:50


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_wagtail112upgrade"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wagtailsitepage",
            old_name="image_desktop",
            new_name="site_screenshot",
        ),
        migrations.RemoveField(
            model_name="wagtailsitepage",
            name="image_phone",
        ),
        migrations.RemoveField(
            model_name="wagtailsitepage",
            name="image_tablet",
        ),
    ]
