# Generated by Django 3.2.13 on 2023-09-04 23:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_submitformfield_clean_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wagtailcompanypage',
            name='coords',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator('-?[0-9\\.]+,\\s?-?[0-9\\.]+')]),
        ),
    ]
