profile = "madewithwagtail"
cluster = "madewithwagtail-production"
task_definition = "madewithwagtail-production-app"
container_name = "app"
log_group = "ecs-tool"

[deploy]
services = ["app"]

[ejson]
pick_keys = ["common", "production"]
kms_key = "alias/madewithwagtail-production"
name = "/madewithwagtail/production/ssm"